#!/usr/bin/with-contenv sh
# The above is how to run on S6 overlay absorbing all the needed env vars

export DOCKER_CERT_PATH=/mnt/certs

# As per runit, don't put this in the background!
/usr/local/bin/portster
